version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10
    working_directory: ~/repo

    steps:
      # checkout branch
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.cache
            - /home/circleci/.cache
          key: v3-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: "Jest tests"
          command: yarn test -w2
      - run:
          name: "Linting"
          command: yarn lint
      - run:
          name: "Cypress"
          command: yarn cypress:ci
      - run:
          name: "Report failing master"
          command: ~/repo/.circleci/notify_failure.sh
          when: on_fail

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
